export const formatFile = {
  jpg: "image/jpeg",
  png: "image/png",
  svg: "image/svg+xml",
  webp: "image/webp",
  audio: "audio/mpeg",
  mp4: "video/mp4",
  zip: "application/zip",
  pdf: "application/pdf",
  txt: "text/plain",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  apk: "application/vnd.android.package-archive",
  pem: "application/x-pem-file",
  md: "text/markdown",
  html: "text/html",
  css: "text/css",
  php: "application/octet-stream",
  js: "application/javascript",
  rs: "application/rls-services+xml",
  java: "text/x-java",
  rb: "application/x-ruby",
  cpp: "text/x-c++src",
  sh: "text/x-sh",
};
